# -*- coding: utf-8 -*-
"""ban_user.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1edH8b1K7cKyLT1KwsEzdNLWz6vjLaCDW
"""

import logging
from datetime import datetime, timedelta

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

class BanManager:
    def __init__(self):
        # Initialize data structures for tracking users/messages
        self.ban_list = set()
        self.user_spam_records = {}

    def classify_message(self, message, user_id):
        """
        Classify the message into one of three categories:
        1. Not spam
        2. Likely or definite spam (delete message and track offenses)
        3. Ban user after repeated offenses

        :param message: str, the content of the message
        :param user_id: str, the ID of the user who sent the message
        :return: str, classification result
        """
        if self.is_definite_spam(message) or self.is_likely_spam(message):
            return self._handle_spam(user_id)
        return "Not spam: Message allowed."

    def is_definite_spam(self, message):
        """Detect definite spam using strict rules."""
        spam_keywords = ["phishing", "scam", "adult content", "free money"]
        return any(keyword in message.lower() for keyword in spam_keywords)

    def is_likely_spam(self, message):
        """Detect likely spam using broader rules."""
        suspicious_phrases = ["click here", "limited offer", "join now"]
        return any(phrase in message.lower() for phrase in suspicious_phrases)

    def _handle_spam(self, user_id):
        """Handle spam by tracking offenses and banning if necessary."""
        now = datetime.now()
        if user_id not in self.user_spam_records:
            self.user_spam_records[user_id] = []

        # Clean up old offenses older than 7 days
        self.user_spam_records[user_id] = [
            offense_time for offense_time in self.user_spam_records[user_id]
            if now - offense_time <= timedelta(days=7)
        ]

        # Record the current offense
        self.user_spam_records[user_id].append(now)

        # Define actions based on offense count
        actions = {
            True: lambda: self.ban_user(user_id) or "Definite spam: User banned.",
            len(self.user_spam_records[user_id]) <= 2: lambda: "Spam message deleted: Warning issued.",
        }

        return actions.get(len(self.user_spam_records[user_id]) > 2, lambda: "Spam message deleted: Warning issued.")()

    def ban_user(self, user_id):
        """Ban a user by adding them to the ban list."""
        self.ban_list.add(user_id)
        logging.info(f"User {user_id} has been banned.")

    def is_user_banned(self, user_id):
        """Check if a user is already banned."""
        return user_id in self.ban_list